apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: hello-gin
spec:
  selector:
    matchLabels:
      app: hello-gin
  podTargetLabels:
    - app
  podMetricsEndpoints:
    - port: http
